### ISSUE TITLE
Can I pass a Lingy map to Perl?

### ISSUE THREAD

**Issue by PEZ** [lingy-lang/lingy#11]
Where I'm coming from: I'm pondering if we can write an [nREPL](https://github.com/nrepl/nREPL) server for Lingy. Not sure I can pull it off, but how hard can it be? 😄 

There's also a question if we can write the server in Lingy. The main transport for nREPL (supported by most all clients) is Bencode. So I tried this:

```clojure
(ns lingy.nrepl
  (:import Bencode))

(def data {:age 25 :eyes "blue"})

(def bencoded (Bencode/bencode data))

(println bencoded)
```

Which gives me:

```
❯ ./scripts/my-lingy.pm src/lingy/nrepl.ly
unhandled data type at ../lingy/perl/lib/Lingy/Evaluator.pm line 59.
```

I then tried to send along `(perl data)` instead, but that gives:

```
--- 14:Lingy::HashMap
--- Don't know how to print internal value '14:Lingy::HashMap'
...
14:Lingy::HashMap Don't know how to print internal value '14:Lingy::HashMap'
```

I'm really not expecting this to work yet. Just checking if it is supposed to work, and I am maybe holding it wrong?

**Comment by PEZ** [comment]
@ingydotnet So, with the clues I gather from here: https://github.com/ingydotnet/lingy/commit/a8c4d424d67ea446f47049601a5d8c56e6e5678d I get this to work:

```clojure
(ns lingy.nrepl
  (:import Bencode))

(def data {:age 25 :eyes "blue"})

(def bencoded (-> data
                  .unbox
                  Bencode/bencode
                  String.))

(println bencoded)
```

```sh
❯ lingy src/lingy/nrepl.ly
d4::agei25e5::eyes4:bluee
```

Then I don't know how work with the decoded value:

```clojure
(def decoded (Bencode/bdecode bencoded))
(println "decoded: " decoded)
```

Gives:

```
decoded:  ---
:age: '25'
:eyes: blue
...
*** Unrecognized Lingy value printed above ***
```

```clojure
(println "age: " (:age decoded))
```

Gives:

```
Can't call method "isa" on unblessed reference at /Users/pez/Projects/lingy/perl/lib/Lingy/Evaluator.pm line 86.
```

Which both indicates that the decoding works, but that I need to do something with the value to make it a Lingy map? I tried:

I tried:

```clojure
(def decoded-map (Lingy.HashMap. decoded))
```

Which gives:

```
Can't use an undefined value as an ARRAY reference at /Users/pez/Projects/lingy/perl/lib/Lingy/HashMap.pm line 11.
```

**Comment by PEZ** [comment]
It's also interesting to note that `(get decoded :age)` evaluates to `nil` (without croaking).

**Comment by ingydotnet** [comment]
See this example I pushed:
* https://github.com/ingydotnet/lingy/tree/bencode/perl/bencode
* https://github.com/ingydotnet/lingy/blob/bencode/perl/bencode/lib/LingyBencode.pm#L10-L12

I needed to write a wrapper library to unbox the lingy map to a perl hash and then turn the perl result string into a lingy string object. 

I'm working on a lingy.interop library to be able to do this more directly from Lingy.

**Comment by ingydotnet** [comment]
I wrote the last reply without seeing your new comments. (Still waking up)

> @ingydotnet So, with the clues I gather from here: [a8c4d42](https://github.com/ingydotnet/lingy/commit/a8c4d424d67ea446f47049601a5d8c56e6e5678d) I get this to work:
> 
> ```clojure
> (ns lingy.nrepl
>   (:import Bencode))
> 
> (def data {:age 25 :eyes "blue"})
> 
> (def bencoded (-> data
>                   .unbox
>                   Bencode/bencode
>                   String.))
> 
> (println bencoded)
> ```
> 
> ```shell
> ❯ lingy src/lingy/nrepl.ly
> d4::agei25e5::eyes4:bluee
> ```

Oh that's very cool!

> 
> Then I don't know how work with the decoded value:
> 
> ```clojure
> (def decoded (Bencode/bdecode bencoded))
> (println "decoded: " decoded)
> ```
> 
> Gives:
> 
> ```
> decoded:  ---
> :age: '25'
> :eyes: blue
> ...
> *** Unrecognized Lingy value printed above ***
> ```

You _simply_ need to do this:
```
lingy.nrepl=> (perl "RT->env->{space}{'decoded-map'} =  Lingy::HashMap->new([%{RT->env->{space}{decoded}}])")
{:age 25, :eyes blue}
lingy.nrepl=> decoded-map 
{:age 25, :eyes blue}
```

:joy:  j/k

You got lucky with the `String.` constructor because it matched the `Lingy::String->new($str)` internal Perl constructor, but the `(HashMap. {...})` constructor usage does not match the internal `Lingy::HashMap->new([ list-of-values ])`, and I can't even think of how I could do it any simpler than the above `perl` eval (in the current implementation.

We need to make some improvements.

I could make the Lingy::HashMap constructor expect that or we can add a function to `lingy.interop` (or both). What do you think?

**Comment by PEZ** [comment]
Did you find my PR? (Afk, so keeping my comment short 😀)

**Comment by ingydotnet** [comment]
Old
